GO
CREATE DATABASE EDUCBTAOFICIAL
GO
USE EDUCBTAOFICIAL
GO


/*---------------------------------------------------TABLAS PRYMARYS*/
CREATE TABLE TBL_TIPO_ROL(
ID_TIPO_ROL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TIPO_ROL VARCHAR(30)NOT NULL UNIQUE
)

INSERT INTO TBL_TIPO_ROL (NOMBRE_TIPO_ROL) VALUES
    ('ADMINISTRADOR'),
    ('ALUMNO'),
    ('DOCENTE'),
    ('FAMILIAR');

	SELECT * FROM TBL_TIPO_ROL

CREATE TABLE TBL_SEXOS(
ID_SEXOS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_SEXO VARCHAR(30)NOT NULL UNIQUE
)
INSERT INTO TBL_SEXOS (NOMBRE_SEXO) VALUES
    ('MASCULINO'),
    ('FEMENINO');



CREATE TABLE TBL_ACTIVOS_CUENTA(
ID_ACTIVOS_CUENTA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ACTIVOS_CUENTA VARCHAR(30)NOT NULL UNIQUE
)
INSERT INTO TBL_ACTIVOS_CUENTA (NOMBRE_ACTIVOS_CUENTA) VALUES
    ('ACTIVO'),
    ('BLOQUEADA');

CREATE TABLE TBL_TRASLADO(
ID_TRASLADO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TRASLADO VARCHAR(20)NOT NULL UNIQUE
)
INSERT INTO TBL_TRASLADO(NOMBRE_TRASLADO) VALUES
    ('VIAJAS'),
    ('RENTAS');

CREATE TABLE TBL_TRASLADO_TRANSPORTE(
ID_TRASLADO_TRANSPORTE INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TRASLADO_TRANSPORTE VARCHAR(20)NOT NULL UNIQUE
)

INSERT INTO TBL_TRASLADO_TRANSPORTE(NOMBRE_TRASLADO_TRANSPORTE) VALUES
    ('CAMINANDO'),('MICROBUS'),('URBAN'),('MOTOCICLETA'),('TAXI'),('AUTOMOVIL PRIVADO'),
    ('BICICLETA');

CREATE TABLE TBL_ASIGNATURAS(
ID_ASIGNATURA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ASIGNATURA VARCHAR(40)NOT NULL UNIQUE
)
INSERT INTO TBL_ASIGNATURAS(NOMBRE_ASIGNATURA) VALUES
    ('ESPAÑOL'),('MATEMATICAS'),('CIENCIAS'),('PSICOLOGIA'),('EOYE'),('HISTORIA'),
    ('EDUCACION FISICA');

CREATE TABLE TBL_GRADOS(
ID_GRADO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_GRADO INT NOT NULL UNIQUE
)
INSERT INTO TBL_GRADOS(NOMBRE_GRADO) VALUES
    (1),(2),(3),(4),(5),(6);

CREATE TABLE TBL_GRUPOS(
ID_GRUPOS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_GRUPOS VARCHAR(3)NOT NULL UNIQUE
)
INSERT INTO TBL_GRUPOS(NOMBRE_GRUPOS) VALUES
    ('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H');

CREATE TABLE TBL_PREGUNTAS(
ID_PREGUNTAS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PREGUNTAS VARCHAR(100)NOT NULL UNIQUE
)

INSERT INTO TBL_PREGUNTAS (NOMBRE_PREGUNTAS)Values ('¿DONDE NACISTE?'),('¿COMO SE LLAMA TU PERRO?'),('¿NOMBRE DE MARCA DE TUS TENNIS FAVORITAS?'),('¿NOMBRE DE TU MADRE?'),
('¿NOMBRE DE TU PADRE'),('¿NOMBRE DE TU EX?'),('¿COMO SE LLAMA TU PERSONAJE FAVORITO?')

CREATE TABLE TBL_CARRERAS_TECNICAS(
ID_CARRERA_TECNICA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CARRERA_TECNICA VARCHAR(200)NOT NULL UNIQUE,
DESCRIPCION_CARRERA_TECNICA VARCHAR(MAX) NOT NULL,
FOTO_CARRERA_TECNICA VARBINARY(MAX)
)

INSERT INTO TBL_CARRERAS_TECNICAS(NOMBRE_CARRERA_TECNICA,DESCRIPCION_CARRERA_TECNICA)VALUES
('TECNICO EN PROGRAMACION','TECNICO EN PROGRAMACION'),('TECNICO EN CONTADURIA','TECNICO EN CONTADURIA')

CREATE TABLE TBL_CLINICAS(
ID_CLINICAS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CLINICAS VARCHAR(100)NOT NULL UNIQUE
)
INSERT INTO TBL_CLINICAS(NOMBRE_CLINICAS) VALUES
    ('FOVIISTE'),('ISSTE'),('IMSS');

CREATE TABLE TBL_PAISES(
ID_PAIS INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_PAIS VARCHAR(250)NOT NULL UNIQUE,
FOTO_PAIS VARBINARY(MAX)
)
INSERT INTO TBL_PAISES(NOMBRE_PAIS)VALUES('MEXICO')

CREATE TABLE TBL_ESTADOS(
ID_ESTADO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ESTADO VARCHAR(250)NOT NULL UNIQUE,
FOTO_ESTADO VARBINARY(MAX)
)
INSERT INTO TBL_ESTADOS (NOMBRE_ESTADO) VALUES
('AGUASCALIENTES'),
('BAJA CALIFORNIA'),
('BAJA CALIFORNIA SUR'),
('CAMPECHE'),
('CHIAPAS'),
('CHIHUAHUA'),
('CIUDAD DE MÉXICO / DISTRITO FEDERAL'),
('COAHUILA'),
('COLIMA'),
('DURANGO'),
('ESTADO DE MÉXICO'),
('GUANAJUATO'),
('GUERRERO'),
('HIDALGO'),
('JALISCO'),
('MICHOACÁN'),
('MORELOS'),
('NAYARIT'),
('NUEVO LEÓN'),
('OAXACA'),
('PUEBLA'),
('QUERÉTARO'),
('QUINTANA ROO'),
('SAN LUIS POTOSÍ'),
('SINALOA'),
('SONORA'),
('TABASCO'),
('TAMAULIPAS'),
('TLAXCALA'),
('VERACRUZ'),
('YUCATÁN'),
('ZACATECAS');


CREATE TABLE TBL_RELACION_FAMILIAR(
ID_RELACION_FAMILIAR INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_RELACION_FAMILIAR VARCHAR(50) NOT NULL UNIQUE
)
INSERT INTO TBL_RELACION_FAMILIAR (NOMBRE_RELACION_FAMILIAR) VALUES
('Padre'),
('Madre'),
('Hermano'),
('Hermana'),
('Abuelo'),
('Abuela'),
('Tío'),
('Tía'),
('Primo'),
('Prima'),
('Cuñado'),
('Cuñada'),
('Suegro'),
('Suegra');

CREATE TABLE TBL_MOTIVO_CREDENCIAL(
ID_MOTIVO_CREDENCIAL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_MOTIVO_CREDENCIAL VARCHAR(50)NOT NULL UNIQUE
)
INSERT INTO TBL_MOTIVO_CREDENCIAL(NOMBRE_MOTIVO_CREDENCIAL)VALUES('EXTRAVIO'),('CADUCO'),('MALAS CONDICIONES')

CREATE TABLE TBL_ACTIVIDADES_ESCOLARES(
ID_ACTIVIDAD_ESCOLAR INT IDENTITY(1,1) PRIMARY KEY,
TITULO_ACTIVIDAD VARCHAR(250)NOT NULL,
DESCRIPCION_ACTIVIDAD VARCHAR(MAX)NOT NULL,
IMAGEN_ACTVIDAD VARBINARY(MAX)
)

/*--------------------------------------------------------TABLAS CON ENLACES DE FOREING KEY*/
	CREATE TABLE TBL_USUARIOS (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    APP_USUARIO VARCHAR(100) NOT NULL,
    APM_USUARIO VARCHAR(100),
    FECHA_NACIMIENTO_USUARIO DATETIME,
    TOKEN_USUARIO VARCHAR(8)not null,
    CORREO_USUARIO VARCHAR(50) UNIQUE NOT NULL,
    PWD_USUARIO VARCHAR(20) NOT NULL,
    PHONE_USUARIO BIGINT, 
	IP_USUARIO varchar(50)not null,
    IDRol INT,
    IDSexo INT,
	IDCuentaActivo int,
	IDPregunta int,
	RespuestaPregunta VARCHAR(255),
	FOREIGN KEY (IDRol) REFERENCES TBL_TIPO_ROL(ID_TIPO_ROL),
    FOREIGN KEY (IDSexo) REFERENCES TBL_SEXOS(ID_SEXOS),
	FOREIGN KEY (IDCuentaActivo) REFERENCES TBL_ACTIVOS_CUENTA (ID_ACTIVOS_CUENTA),
	FOREIGN KEY (IDPregunta) REFERENCES TBL_PREGUNTAS (ID_PREGUNTAS),
);

	select * from TBL_USUARIOS
	

	CREATE TABLE TBL_DOCENTES(
	ID_DOCENTES INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_DOCENTES VARCHAR(50) NOT NULL,
	APP_DOCENTES VARCHAR(50) NOT NULL,
	APM_DOCENTES VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO_DOCENTES DATETIME NOT NULL,
	NOCONTTROL_DOCENTES BIGINT NOT NULL UNIQUE,
	TELEFONO_DOCENTES BIGINT NOT NULL UNIQUE,
	FOTO_DOCENTES VARBINARY(MAX),
	SEGURO_SOCIAL_DOCENTES BIGINT UNIQUE NOT NULL,
	IDSEXO INT,
    IDUSUARIO INT ,
	IDCLINICA INT,
	FOREIGN KEY (IDSEXO) REFERENCES TBL_SEXOS(ID_SEXOS),
    FOREIGN KEY (IDUSUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO),
	FOREIGN KEY (IDCLINICA) REFERENCES TBL_CLINICAS(ID_CLINICAS),
)

INSERT INTO TBL_DOCENTES (NOMBRE_DOCENTES, APP_DOCENTES, APM_DOCENTES, FECHA_NACIMIENTO_DOCENTES, NOCONTTROL_DOCENTES, TELEFONO_DOCENTES, SEGURO_SOCIAL_DOCENTES, IDSEXO, IDUSUARIO, IDCLINICA)
VALUES ('PEDRO', 'MANUEL', 'TORRES', '1999-01-01', '223456789012345', 22454555, '22345678901234', 1, 3, 1);


CREATE TABLE TBL_ALUMNOS(
	ID_ALUMNOS INT IDENTITY(1,1) PRIMARY KEY,
	NOMBRE_ALUMNOS VARCHAR(100)NOT NULL,
	APP_ALUMNOS VARCHAR(100)NOT NULL,
	APM_ALUMNOS VARCHAR(100)NOT NULL,
	FOTO_ALUMNOS VARBINARY(MAX),
	FECHA_NACIMIENTO_ALUMNOS DATETIME NOT NULL,
	CURP_ALUMNOS VARCHAR(50)NOT NULL UNIQUE,
	NOCONTROL_ALUMNOS BIGINT NOT NULL UNIQUE,
	TELEFONO_ALUMNOS BIGINT NOT NULL UNIQUE,
	SEGURO_SOCIAL_ALUMNOS BIGINT NOT NULL UNIQUE,
	CUENTACREDENCIAL_ALUMNOS VARCHAR(2) NOT NULL,
	IDSEXO INT,
	FOREIGN KEY (IDSEXO) REFERENCES TBL_SEXOS(ID_SEXOS),
	IDUSUARIO INT,
	FOREIGN KEY (IDUSUARIO) REFERENCES  TBL_USUARIOS(ID_USUARIO),
	IDCLINICA INT,
	FOREIGN KEY (IDCLINICA) REFERENCES  TBL_CLINICAS(ID_CLINICAS),
	IDGRADO INT,
	FOREIGN KEY (IDGRADO) REFERENCES  TBL_GRADOS(ID_GRADO),
	IDGRUPO INT,
	FOREIGN KEY (IDGRUPO) REFERENCES  TBL_GRUPOS(ID_GRUPOS),
	IDTRASLADO INT,
	FOREIGN KEY (IDTRASLADO) REFERENCES  TBL_TRASLADO(ID_TRASLADO),
	IDTRASLADOTRANSPORTE INT,
	FOREIGN KEY (IDTRASLADOTRANSPORTE) REFERENCES  TBL_TRASLADO_TRANSPORTE(ID_TRASLADO_TRANSPORTE),
	IDCARRERATECNICA INT,
	FOREIGN KEY (IDCARRERATECNICA) REFERENCES  TBL_CARRERAS_TECNICAS(ID_CARRERA_TECNICA),
	IDPAIS INT,
	FOREIGN KEY (IDPAIS) REFERENCES  TBL_PAISES(ID_PAIS),
	IDESTADO INT,
	FOREIGN KEY (IDESTADO) REFERENCES  TBL_ESTADOS(ID_ESTADO),
	MUNICIPIO_ALUMNOS VARCHAR(100)NOT NULL,
	COMUNIDAD_ALUMNOS VARCHAR(100)NOT NULL,
	CALLE_ALUMNOS VARCHAR(100)NOT NULL,
	PROC_SEC_ALUMNO VARCHAR(100) NOT NULL,
	NOMBRE_FAMILIAR_ALUMNO VARCHAR(100)NOT NULL,
	APP_FAMILIAR_ALUMNO VARCHAR(100)NOT NULL,
	APM_FAMILIAR_ALUMNO VARCHAR(100)NOT NULL,
	IDRELACIONFAMILIAR INT,
	FOREIGN KEY (IDRELACIONFAMILIAR) REFERENCES  TBL_RELACION_FAMILIAR(ID_RELACION_FAMILIAR),
	NUMERO_TELEFONO_FAMILIAR_ALUMNO BIGINT NOT NULL,
	FOTO_FAMILIAR_ALUMNO VARBINARY(MAX)
)

-- Insertando datos ficticios en la tabla de alumnos
INSERT INTO TBL_ALUMNOS (
    NOMBRE_ALUMNOS,
    APP_ALUMNOS,
    APM_ALUMNOS,
    FOTO_ALUMNOS,
    FECHA_NACIMIENTO_ALUMNOS,
    CURP_ALUMNOS,
    NOCONTROL_ALUMNOS,
    TELEFONO_ALUMNOS,
    SEGURO_SOCIAL_ALUMNOS,
    CUENTACREDENCIAL_ALUMNOS,
    IDSEXO,
    IDUSUARIO,
    IDCLINICA,
    IDGRADO,
    IDGRUPO,
    IDTRASLADO,
    IDTRASLADOTRANSPORTE,
    IDCARRERATECNICA,
    IDPAIS,
    IDESTADO,
    MUNICIPIO_ALUMNOS,
    COMUNIDAD_ALUMNOS,
    CALLE_ALUMNOS,
    PROC_SEC_ALUMNO,
    NOMBRE_FAMILIAR_ALUMNO,
    APP_FAMILIAR_ALUMNO,
    APM_FAMILIAR_ALUMNO,
    IDRELACIONFAMILIAR,
    NUMERO_TELEFONO_FAMILIAR_ALUMNO,
    FOTO_FAMILIAR_ALUMNO
)
VALUES (
    'JOSE',
    'SANTOS',
    'GUZMAN',
    NULL, -- Aquí podrías insertar la imagen en formato VARBINARY
    '2008-05-15',
    'PERD900515HMCLRD02',
    810,
    155,
    110,
    'SI', -- I cuenta de credencial (si aplica)
    1, -- ID del sexo (1 para masculino, 2 para femenino)
    1, -- ID del usuario relacionado (debe existir en TBL_USUARIOS)
    1, -- ID de la clínica (debe existir en TBL_CLINICAS)
    3, -- ID del grado (debe existir en TBL_GRADOS)
    2, -- ID del grupo (debe existir en TBL_GRUPOS)
    1, -- ID del traslado (debe existir en TBL_TRASLADO)
    2, -- ID del transporte del traslado (debe existir en TBL_TRASLADO_TRANSPORTE)
    3, -- ID de la carrera técnica (debe existir en TBL_CARRERAS_TECNICAS)
    1, -- ID del país (debe existir en TBL_PAISES)
    5, -- ID del estado (debe existir en TBL_ESTADOS)
    'Ciudad de México',
    'Colonia Centro',
    'Calle 123',
    'Preparatoria XYZ',
    'María',
    'García',
    'López',
    5, -- ID de la relación familiar (debe existir en TBL_RELACION_FAMILIAR)
    155,
    NULL -- Aquí podrías insertar la imagen del familiar en formato VARBINARY
);


CREATE TABLE TBL_MENSAJES_MOTIVO_CREDENCIAL(
ID_MENSAJES_MOTIVO_CREDENCIAL INT IDENTITY(1,1) PRIMARY KEY,
IDALUMNO INT,
FOREIGN KEY (IDALUMNO) REFERENCES  TBL_ALUMNOS(ID_ALUMNOS),
IDMOTIVO INT,
FOREIGN KEY (IDMOTIVO) REFERENCES  TBL_MOTIVO_CREDENCIAL(ID_MOTIVO_CREDENCIAL),
FECHA_MOTIVO_CREDENCIAL DATETIME
)
insert into TBL_MENSAJES_MOTIVO_CREDENCIAL
(IDALUMNO,IDMOTIVO,FECHA_MOTIVO_CREDENCIAL) VALUES
(3,3,'2020-10-02')


CREATE TABLE TBL_CREDENCIALES_ESCOLARES(
ID_CREDENCIAL_ESCOLAR INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CREDENCIAL_ESCOLAR VARCHAR(100),
APP_CREDENCIAL_ESCOLAR VARCHAR(100),
APM_CREDENCIAL_ESCOLAR VARCHAR(100),
CARRERA_CREDENCIAL_ESCOLAR VARCHAR(100),
GRUPO_CREDENCIAL_ESCOLAR VARCHAR(2),
CURP_CREDENCIAL_ESCOLAR VARCHAR(22),
NOCONTROL_CREDENCIAL_ESCOLAR VARCHAR(22),
SEGSOCIAL_CREDENCIAL_ESCOLAR VARCHAR(22),
IDALUMNOCREDE INT,
FOREIGN KEY (IDALUMNOCREDE) REFERENCES  TBL_ALUMNOS(ID_ALUMNOS),
)
SELECT * FROM TBL_CREDENCIALES_ESCOLARES
INSERT INTO TBL_CREDENCIALES_ESCOLARES
(NOMBRE_CREDENCIAL_ESCOLAR,APP_CREDENCIAL_ESCOLAR,APM_CREDENCIAL_ESCOLAR,CARRERA_CREDENCIAL_ESCOLAR,
GRUPO_CREDENCIAL_ESCOLAR,CURP_CREDENCIAL_ESCOLAR,NOCONTROL_CREDENCIAL_ESCOLAR,SEGSOCIAL_CREDENCIAL_ESCOLAR,IDALUMNOCREDE)
VALUES
('JESUS','MTZ','HDEZ','TECNICO EN OFIMATICA','B','123123121313','1005534234562345','155456789012',2)





-- ESTE VA PARTE DEL FRONTEND LA PAGINA PRINCIPAL
CREATE TABLE TBL_WELCOME(
ID_WELCOME INT IDENTITY(1,1) PRIMARY KEY,
WELCOME_TEXT TEXT
)
INSERT INTO TBL_WELCOME (WELCOME_TEXT)VALUES('El Centro de Bachillerato Tecnológico Agropecuario No. 5 inicia sus actividades el 02 de octubre de 1972 en la ciudad de Huejutla de Reyes Hidalgo, se encuentra localizado al norte de la ciudad, sobre el Boulevard Adolfo López Mateos s/n colonia aviación civil. Es un gra privilegio poder forjar a las futuras generaciones desde hace ya aproximadamente 50 años y de esta manera estar contribuyendo a nuestra comunidad, el C.B.T.A. 5 de Huejutla, Hgo. ha formado técnicos de calidad, con un claro compromiso social. ¡Bienvenidos!')
SELECT * FROM TBL_WELCOME

CREATE TABLE TBL_MISION(
ID_MISION INT IDENTITY(1,1)PRIMARY KEY,
MISION_TEXT TEXT
)
INSERT INTO TBL_MISION (MISION_TEXT)VALUES('Contribuir en la formación integral de individuos dotados de valores, conocimientos, habilidades y destrezas en el ámbito tecnológico y en el nivel bachillerato, que le permite incorporarse al trabajo productivo basado en competencias laborales como agente de cambio y /o continuar sus estudios en el nivel superior.')
SELECT * FROM TBL_MISION

CREATE TABLE TBL_VISION(
ID_VISION INT IDENTITY(1,1)PRIMARY KEY,
VISION_TEXT TEXT
)
INSERT INTO TBL_VISION (VISION_TEXT)VALUES
('Ser una institución educativa plenamente consolidada que represente una de las mejores opciones de educación tecnológica del nivel medio superior, donde la calidad sea el eje sobre el cual gire nuestra casa de estudios.')

SELECT * FROM TBL_VISION
/*--------------------------------------------EMPIEZAN LAS BITACORAS Y LOS TRIGGERS*/
CREATE TABLE BITACORA_USUARIOS (
    ID_BITACORA INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT,
    NOMBRE_USUARIO VARCHAR(255),
    ACCION_REALIZADA VARCHAR(20),
    DETALLES_ACCION VARCHAR(MAX),
    FECHA_ACCESO DATETIME,
    IP_ACCESO VARCHAR(50)
);

CREATE TABLE BITACORA_SESION (
    ID_SESION INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT,
    NOMBRE_USUARIO VARCHAR(255),
    CORREO_USUARIO VARCHAR(255),
    FECHA_INICIO DATETIME,
    IP_USUARIO VARCHAR(50),
    URL_SOLICITADA VARCHAR(255)
);

select * from BITACORA_USUARIOS
select * from BITACORA_SESION
select * from TBL_USUARIOS
select * from TBL_ASIGNATURAS
select * from TBL_CARRERAS_TECNICAS
select * from TBL_PAISES
select * from TBL_USUARIOS
select * from TBL_ALUMNOS
SELECT * FROM TBL_MENSAJES_MOTIVO_CREDENCIAL
SELECT * FROM TBL_CREDENCIAL_CREADA
SELECT * FROM TBL_DOCENTES
select * from TBL_ASISTENCIAS
select * from TBL_HORARIOS_ESCOLARES

--ALTER TABLE TBL_HORARIOS_ESCOLARES
--ADD DIAS_HORARIOS VARCHAR(MAX);

CREATE TABLE TBL_HORARIOS_ESCOLARES(
    ID_HORARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_ASIGNATURA INT NOT NULL,
    ID_DOCENTE INT NOT NULL,
    ID_GRADO INT NOT NULL,
    ID_GRUPO INT NOT NULL,
    ID_CARRERA_TECNICA INT NOT NULL,
    CICLO_ESCOLAR VARCHAR(10) NOT NULL,
	DIAS_HORARIOS VARCHAR(MAX),
    FOREIGN KEY (ID_ASIGNATURA) REFERENCES TBL_ASIGNATURAS(ID_ASIGNATURA),
    FOREIGN KEY (ID_DOCENTE) REFERENCES TBL_DOCENTES(ID_DOCENTES),
    FOREIGN KEY (ID_GRADO) REFERENCES TBL_GRADOS(ID_GRADO),
    FOREIGN KEY (ID_GRUPO) REFERENCES TBL_GRUPOS(ID_GRUPOS),
    FOREIGN KEY (ID_CARRERA_TECNICA) REFERENCES TBL_CARRERAS_TECNICAS(ID_CARRERA_TECNICA)
);

CREATE TABLE TBL_HORARIO_ALUMNOS (
    ID_HORARIO_ALUMNO INT IDENTITY(1,1) PRIMARY KEY,
    ID_HORARIO INT NOT NULL,
    ID_ALUMNO INT NOT NULL,
    FECHA_INSCRIPCION DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_HORARIO) REFERENCES TBL_HORARIOS_ESCOLARES(ID_HORARIO),
    FOREIGN KEY (ID_ALUMNO) REFERENCES TBL_ALUMNOS(ID_ALUMNOS)
);
f
SELECT * FROM TBL_HORARIO_ALUMNOS

CREATE TABLE TBL_ASISTENCIAS (
    ID_ASISTENCIA INT IDENTITY(1,1) PRIMARY KEY,
    ID_ALUMNO INT NOT NULL,
    ID_HORARIO INT NOT NULL,
    FECHA DATETIME NOT NULL,
    ESTADO_ASISTENCIA VARCHAR(50) NOT NULL,
    COMENTARIOS VARCHAR(MAX),
    FOREIGN KEY (ID_ALUMNO) REFERENCES TBL_ALUMNOS(ID_ALUMNOS),
    FOREIGN KEY (ID_HORARIO) REFERENCES TBL_HORARIOS_ESCOLARES(ID_HORARIO)
);



delete from TBL_ASISTENCIAS
delete from TBL_HORARIO_ALUMNOS
delete from TBL_HORARIOS_ESCOLARES